[map]

[map.zoom]
a = 1.0 # exp zoom equation, outside factor
b = 1.0 # exp zoom equation, inner factor
increment = 0.1 # the smallest change in camera zoom
max = 4.0 # the maximum allowable camera zoom
min = 0.2 # the minimum allowable camera zoom

[grid]
backbuffer = true # enables the backbuffer object during generation
alpha = 1.0 # the standard alpha of the grid object against the background

[grid.draw]
max = 0.25 # how big can a cell of the grid be with respect to the size of the screen
min = 0.08 # how small a cell of the grid can be with respect to the size of the screen

[grid.fade] # everything related to the transition effects
enabled = true # enables the fading transition
timer = 0.5 # the transition time (in seconds) when transitioning grid zoom levels

[grid.mode] # the colors of the grid at different modes
navigation = 0xFF0044FF
navigation_drag = 0xFF0044FF

[debug]

[debug.update_watch]
flash_times = 3
flash_length = 1.1
